force-app/main/default/objects/Closing_hz__c/Closing_hz__c.object-meta.xml
<CustomObject>
    <label>Closing</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Closing ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Closing_hz__c/fields/Listing_hz__c.field-meta.xml
<CustomField>
    <fullName>Listing_hz__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Listing</label>
    <referenceTo>Listing_hz__c</referenceTo>
    <relationshipLabel>Closings</relationshipLabel>
    <relationshipName>Closings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Closing_hz__c/recordTypes/Rent.recordType-meta.xml
<RecordType>
    <fullName>Rent</fullName>
    <active>true</active>
    <label>Rent</label>
</RecordType>

force-app/main/default/objects/Listing_hz__c/Listing_hz__c.object-meta.xml
<CustomObject>
    <label>Listing</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Listing_hz__c/fields/Broker_s_Listing_ID__c.field-meta.xml
<CustomField>
    <fullName>Broker_s_Listing_ID__c</fullName>
    <label>Broker&apos;s Listing ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/Completion_Status__c.field-meta.xml
<CustomField>
    <fullName>Completion_Status__c</fullName>
    <label>Completion Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Off Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/Description_hz__c.field-meta.xml
<CustomField>
    <fullName>Description_hz__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/FullBathrooms_hz__c.field-meta.xml
<CustomField>
    <fullName>FullBathrooms_hz__c</fullName>
    <label>Bathrooms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/Listing_Agent_Phone__c.field-meta.xml
<CustomField>
    <fullName>Listing_Agent_Phone__c</fullName>
    <label>Listing Agent Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/ListingPrice_hz__c.field-meta.xml
<CustomField>
    <fullName>ListingPrice_hz__c</fullName>
    <label>Price</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/ListingType__c.field-meta.xml
<CustomField>
    <fullName>ListingType__c</fullName>
    <label>Listing Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Rent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/Property_Propertyfinder__c.field-meta.xml
<CustomField>
    <fullName>Property_Propertyfinder__c</fullName>
    <label>Property - Propertyfinder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/PropertyType__c.field-meta.xml
<CustomField>
    <fullName>PropertyType__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>Townhouse</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Duplex</fullName>
            </value>
            <value>
                <fullName>Penthouse</fullName>
            </value>
            <value>
                <fullName>Land</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Commercial Lease</fullName>
            </value>
            <value>
                <fullName>Commercial Sale</fullName>
            </value>
            <value>
                <fullName>Business/Commercial</fullName>
            </value>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Residential Lease</fullName>
            </value>
            <value>
                <fullName>Residential Rental</fullName>
            </value>
            <value>
                <fullName>Waterfront</fullName>
            </value>
            <value>
                <fullName>Farm</fullName>
            </value>
            <value>
                <fullName>Boat Dock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/RERA_Permit_Number__c.field-meta.xml
<CustomField>
    <fullName>RERA_Permit_Number__c</fullName>
    <description>Trakheesi Permit Number / Listing Permit Number</description>
    <label>RERA Permit Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/TotalArea_hz__c.field-meta.xml
<CustomField>
    <fullName>TotalArea_hz__c</fullName>
    <label>Size</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/recordTypes/Rent.recordType-meta.xml
<RecordType>
    <fullName>Rent</fullName>
    <active>true</active>
    <label>Rent</label>
</RecordType>

force-app/main/default/objects/Property_hz__c/Property_hz__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_hz__c/fields/Address_hz__c.field-meta.xml
<CustomField>
    <fullName>Address_hz__c</fullName>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/Area_hz__c.field-meta.xml
<CustomField>
    <fullName>Area_hz__c</fullName>
    <label>Area</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/Bedrooms_hz__c.field-meta.xml
<CustomField>
    <fullName>Bedrooms_hz__c</fullName>
    <label>Bedrooms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/City_Dubizzle__c.field-meta.xml
<CustomField>
    <fullName>City_Dubizzle__c</fullName>
    <label>City - Dubizzle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dubai</fullName>
            </value>
            <value>
                <fullName>Abu Dhabi</fullName>
            </value>
            <value>
                <fullName>Cairo</fullName>
            </value>
            <value>
                <fullName>Alexandria</fullName>
            </value>
            <value>
                <fullName>Jeddah</fullName>
            </value>
            <value>
                <fullName>Riyadh</fullName>
            </value>
            <value>
                <fullName>Ras al Khaimeh</fullName>
            </value>
            <value>
                <fullName>Sharjah</fullName>
            </value>
            <value>
                <fullName>Fujeirah</fullName>
            </value>
            <value>
                <fullName>Ajman</fullName>
            </value>
            <value>
                <fullName>Umm al Quwain</fullName>
            </value>
            <value>
                <fullName>Dammam and Khobar</fullName>
            </value>
            <value>
                <fullName>Kuwait City</fullName>
            </value>
            <value>
                <fullName>Doha</fullName>
            </value>
            <value>
                <fullName>Manama</fullName>
            </value>
            <value>
                <fullName>Muscat</fullName>
            </value>
            <value>
                <fullName>Damascus</fullName>
            </value>
            <value>
                <fullName>Amman</fullName>
            </value>
            <value>
                <fullName>Beirut</fullName>
            </value>
            <value>
                <fullName>Algiers</fullName>
            </value>
            <value>
                <fullName>Tripoli</fullName>
            </value>
            <value>
                <fullName>Tunis</fullName>
            </value>
            <value>
                <fullName>Casablanca</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/City_hz__c.field-meta.xml
<CustomField>
    <fullName>City_hz__c</fullName>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/City_Propertyfinder__c.field-meta.xml
<CustomField>
    <fullName>City_Propertyfinder__c</fullName>
    <label>City - Propertyfinder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/CompletionDate_hz__c.field-meta.xml
<CustomField>
    <fullName>CompletionDate_hz__c</fullName>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/Property_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Sub_Type__c</fullName>
    <label>Property Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Residential - Apartment</fullName>
            </value>
            <value>
                <fullName>Residential - Bulk Units</fullName>
            </value>
            <value>
                <fullName>Residential - Bungalow</fullName>
            </value>
            <value>
                <fullName>Residential - Compound</fullName>
            </value>
            <value>
                <fullName>Residential - Duplex</fullName>
            </value>
            <value>
                <fullName>Residential - Full floor</fullName>
            </value>
            <value>
                <fullName>Residential - Half floor</fullName>
            </value>
            <value>
                <fullName>Residential - Land</fullName>
            </value>
            <value>
                <fullName>Residential - Penthouse</fullName>
            </value>
            <value>
                <fullName>Residential - Townhouse</fullName>
            </value>
            <value>
                <fullName>Residential - Villa</fullName>
            </value>
            <value>
                <fullName>Residential - Whole Building</fullName>
            </value>
            <value>
                <fullName>Residential - Labor Camp</fullName>
            </value>
            <value>
                <fullName>Commercial - Bulk Units</fullName>
            </value>
            <value>
                <fullName>Commercial - Full floor</fullName>
            </value>
            <value>
                <fullName>Commercial - Half floor</fullName>
            </value>
            <value>
                <fullName>Commercial - Office Space</fullName>
            </value>
            <value>
                <fullName>Commercial - Plot</fullName>
            </value>
            <value>
                <fullName>Commercial - Retail</fullName>
            </value>
            <value>
                <fullName>Commercial - Shop</fullName>
            </value>
            <value>
                <fullName>Commercial - Show Room</fullName>
            </value>
            <value>
                <fullName>Commercial - Staff Accommodation</fullName>
            </value>
            <value>
                <fullName>Commercial - Villa</fullName>
            </value>
            <value>
                <fullName>Commercial - Warehouse</fullName>
            </value>
            <value>
                <fullName>Commercial - Whole Building</fullName>
            </value>
            <value>
                <fullName>Commercial - Labor Camp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/PropertyOwnerContact__c.field-meta.xml
<CustomField>
    <fullName>PropertyOwnerContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Owned Properties</relationshipLabel>
    <relationshipName>PropertyOwnerContact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/PropertyType__c.field-meta.xml
<CustomField>
    <fullName>PropertyType__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Duplex</fullName>
            </value>
            <value>
                <fullName>Condo</fullName>
            </value>
            <value>
                <fullName>Townhouse</fullName>
            </value>
            <value>
                <fullName>Penthouse</fullName>
            </value>
            <value>
                <fullName>Single Family</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Multi Family</fullName>
            </value>
            <value>
                <fullName>Lot/Land</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Coop</fullName>
            </value>
            <value>
                <fullName>Manufactured</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/State_hz__c.field-meta.xml
<CustomField>
    <fullName>State_hz__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/Sub_Community_Propertyfinder__c.field-meta.xml
<CustomField>
    <fullName>Sub_Community_Propertyfinder__c</fullName>
    <label>Sub Community - Propertyfinder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/TotalArea_hz__c.field-meta.xml
<CustomField>
    <fullName>TotalArea_hz__c</fullName>
    <label>Size</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/recordTypes/Building.recordType-meta.xml
<RecordType>
    <fullName>Building</fullName>
    <active>true</active>
    <label>Building</label>
</RecordType>

force-app/main/default/classes/rentalClosingRecurringTaskBatchTest.cls
@isTest
public class rentalClosingRecurringTaskBatchTest {

    static Contact createLandlordContact(String fname, String lname) {


        
        Contact c = new Contact();
        c.FirstName = fname;
        c.LastName = lname;
        c.ContactType_hz__c = 'Landlord';
        c.LeadSource = 'Portal';
        c.LeadSourceCategory_hz__c  = 'Getthat';
        c.MailingStreet = 'Test';
        c.MailingCity = 'Test';
        c.MailingCountry = 'UAE';
        insert c;
        
        return c;
    }
    
    static Contact createTenantContact(String fname, String lname) {
        
        Contact t = new Contact();
        t.FirstName = fname;
        t.LastName = lname;
        t.ContactType_hz__c = 'Tenant';
        t.LeadSource = 'Portal';
        t.LeadSourceCategory_hz__c  = 'Getthat';
        t.MailingStreet = 'Test';
        t.MailingCity = 'Test';
        t.MailingCountry = 'UAE';
        insert t;
        
        return t;
    }

  
    
    static testMethod void TestUpdateTargetAchieveOnUserBatch() {
        
        
        Date firstDayOfMonth = System.today().toStartOfMonth();
        System.debug('First Day of the Month-->'+firstDayOfMonth);
        Profile p = [SELECT Id FROM Profile WHERE Name='HZ Agent'];
        UserRole testRole = new UserRole(
            Name = 'Renewal Coordinator'
            
        );
        insert testRole;        
        User manager = [SELECT Id FROM User WHERE Name = 'Vansh Mehra'];
        system.debug('Profile Id -->'+p.Id);
        User u = new User(Alias = 'sttst2', Email='standarduser1@tesorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing1', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, MobilePhone = '+91 9326582649', Phone = '+919326582649',
                          TimeZoneSidKey='America/Los_Angeles',UserRoleId=testRole.Id, UserName='standarduser1@tesorg.com',ManagerId = manager.Id);
        Insert u;
        system.debug('User Created-->'+u.Id);
        
     



        System.runAs(u){
            // create test contacts
            Contact Contact1 = createLandlordContact('First1', 'Test1');
            Contact Contact2 = createTenantContact('First2', 'Test2');     

            Property_hz__c pro=new Property_hz__c();
            pro.name ='test';
            pro.Address_hz__c ='Test';
            pro.Area_hz__c ='Test';
            insert pro;

            String recordTypeId1 = Schema.SObjectType.Listing_hz__c.getRecordTypeInfosByName().get('Rent').getRecordTypeId();

    
            Listing_hz__c listing1 = new Listing_hz__c();
            listing1.Name = 'Test1';
            listing1.recordTypeId=recordTypeId1;
            listing1.Status__c = 'Active';
            listing1.ListingType__c = 'Rental';
            listing1.PropertyType__c = 'Apartment';
            listing1.Bedrooms_hz__c = 2;
            listing1.FullBathrooms_hz__c = 2;
            listing1.ListingPrice_hz__c = 1000;
            listing1.City_hz__c = 'Test';
            listing1.State_hz__c = 'Test';
            listing1.Broker_s_Listing_ID__c='Test';
            listing1.Description_hz__c='Testing Area';
            listing1.PropertySubType_hz__c='Industrial';
            listing1.Houzon_Broker_s_Listing_ID__c='Test1';
            listing1.Property_Sub_Type__c='Residential - Apartment';
            listing1.RERA_Permit_Number__c='100';
            listing1.TotalArea_hz__c=1000;
            listing1.Sub_Community_Propertyfinder__c='Test';
            listing1.Community_Propertyfinder__c='Test';
            listing1.Property_Propertyfinder__c='Test';
            listing1.LocationText_Dubizzle__c='Test';
            listing1.City_Propertyfinder__c='test';
            listing1.Price_Unit__c='Price Yearly';
            listing1.Completion_Status__c='Completed';
            listing1.City_Dubizzle__c='Test';
            listing1.Property_Status__c='Rented';
            listing1.Available_from__c=date.today()+1;
            listing1.CompletionDate_hz__c=date.today()+1;
            listing1.PropertyOwnerContact__c=Contact1.Id;
            listing1.Property_hz__c=pro.Id;
            listing1.property_category__c='Commercial';
            listing1.RERA_Expiry_Date__c = Date.newInstance(2024, 04, 21);
            listing1.Bedrooms_hz__c = 2;
            listing1.FullBathrooms_hz__c = 2;
            listing1.TotalArea_hz__c = 500;
            listing1.Listing_Agent_Firstname__c = 'listing agent first';
            listing1.Listing_Agent_Lastname__c = 'listing agent Last';
            listing1.Listing_Agent_Phone__c = '8765456543';
            listing1.Listing_Agent_Email__c = 'listingagent1@test.com';
            listing1.ListingPrice_hz__c = 5000;
            listing1.Propertyfinder_Region__c = 'Abu Dhabi - Al Ghadeer - Al Sabeel Building';
            listing1.City_Propertyfinder__c = 'Abu Dhabi';
            listing1.Community_Propertyfinder__c = 'Al Ghadeer';
            listing1.City_Dubizzle__c = 'Abu Dhabi';
            listing1.OwnerId = u.Id;
            insert listing1;
    
            Date todayPlusNinetyDays = Date.today().addDays(90);

            String recordTypeId = Schema.SObjectType.Closing_hz__c.getRecordTypeInfosByName().get('Rent').getRecordTypeId();
            
            Closing_hz__c closing1 = new Closing_hz__c();
            closing1.Renter__c = Contact2.id;
            closing1.recordTypeId=recordTypeId;
            closing1.Landlord_c__c = Contact1.id;
            closing1.Listing_hz__c = listing1.id;
            closing1.Lease_Terms__c = '3 Month';
            closing1.ClosingDate__c = Date.newInstance(2024, 08, 28);
            closing1.Rental_Agreement_Date__c = date.parse('07/11/2024');
            closing1.Rental_Agreement_End_Date__c = date.parse('10/10/2024');
            closing1.Closing_Status__c = 'Closed';
            closing1.Agent_Commission__c = 1000;
            closing1.TotalCommissionAmount__c = 1000;
            closing1.Rental_Agreement_End_Date__c = todayPlusNinetyDays;
            closing1.OwnerId = u.Id;
            
            Closing_hz__c closing2 = new Closing_hz__c();
            closing2.Renter__c = Contact2.id;
            closing2.recordTypeId=recordTypeId;
            closing2.Landlord_c__c = Contact1.id;
            closing2.Listing_hz__c = listing1.id;
            closing2.Lease_Terms__c = '3 Month';
            closing2.ClosingDate__c = Date.newInstance(2024, 05, 18);
            closing2.Rental_Agreement_Date__c = date.parse('07/11/2024');
            closing2.Rental_Agreement_End_Date__c = date.parse('09/09/2024');
            closing2.Closing_Status__c = 'Closed';
            closing1.TotalCommissionAmount__c = 3000;
            closing2.Agent_Commission__c = 2000;
            closing2.Rental_Agreement_End_Date__c = todayPlusNinetyDays;
            closing2.OwnerId = u.Id;
            
      
            Test.StartTest();
            
            	insert closing1;
                insert closing2;    
          

                rentalClosingRecurringTaskBatch rentalClosing = new rentalClosingRecurringTaskBatch();
                ID batchprocessid = Database.executeBatch(rentalClosing, 1900);
                
                Test.StopTest();  
        }
    }
    @isTest static void testMethod1(){
         
        rentalClosingRecurringTaskBatchScheduler contactTaskSchedule = new rentalClosingRecurringTaskBatchScheduler();
        String sch = '0 0 23 * * ?'; system.schedule('Test Territory Check', sch, contactTaskSchedule); 
    } 


}