force-app/main/default/objects/Listing_hz__c/Listing_hz__c.object-meta.xml
<CustomObject>
    <label>Listing</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PortalListing__c/PortalListing__c.object-meta.xml
<CustomObject>
    <label>Portal Listing</label>
    <nameField>
        <displayFormat>PortalListing-{0000000}</displayFormat>
        <label>Portal Listing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Listings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PortalListing__c/fields/Listing_hz__c.field-meta.xml
<CustomField>
    <fullName>Listing_hz__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Listing</label>
    <referenceTo>Listing_hz__c</referenceTo>
    <relationshipLabel>Listed on these portals</relationshipLabel>
    <relationshipName>Portal_Listings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PortalListing__c/fields/SystemIsActive__c.field-meta.xml
<CustomField>
    <fullName>SystemIsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ListingTriggerHandler.cls
public with sharing class ListingTriggerHandler {
    
    public void OnBeforeInsert(List<Listing_hz__c> newListings){
        for (Listing_hz__c listing : newListings) {
            if (listing.Status__c == 'Active') {
                listing.SystemAllowedForPortals__c = true; 
            } else {
                listing.SystemAllowedForPortals__c = false;
            }
        }
    }

    public void OnBeforeUpdate(List<Listing_hz__c> newListings){
        for (Listing_hz__c listing : newListings) {
            if (listing.Status__c == 'Active') {
                listing.SystemAllowedForPortals__c = true; 
            } else {
                listing.SystemAllowedForPortals__c = false;
                List<PortalListing__c> portalListings = [SELECT Id,Listing_hz__c,SystemIsActive__c FROM PortalListing__c WHERE Listing_hz__c IN : newListings];
                List<PortalListing__c> portalListings_toUpdate = new List<PortalListing__c>();
                if(portalListings.size()>0){
                    for(PortalListing__c portalListing : portalListings){
                        portalListing.SystemIsActive__c = false;
                        portalListings_toUpdate.add(portalListing);
                    }
                    update portalListings_toUpdate;
                }
            }
        }
    }
}