force-app/main/default/objects/Listing_hz__c/Listing_hz__c.object-meta.xml
<CustomObject>
    <label>Listing</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Listing_hz__c/fields/Broker_s_Listing_ID__c.field-meta.xml
<CustomField>
    <fullName>Broker_s_Listing_ID__c</fullName>
    <label>Broker&apos;s Listing ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/Description_Arabic__c.field-meta.xml
<CustomField>
    <fullName>Description_Arabic__c</fullName>
    <label>Description (Arabic)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/Description_hz__c.field-meta.xml
<CustomField>
    <fullName>Description_hz__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/Feature_1__c.field-meta.xml
<CustomField>
    <fullName>Feature_1__c</fullName>
    <label>Feature 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/Feature_2__c.field-meta.xml
<CustomField>
    <fullName>Feature_2__c</fullName>
    <label>Feature 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/Feature_3__c.field-meta.xml
<CustomField>
    <fullName>Feature_3__c</fullName>
    <label>Feature 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/Feature_4__c.field-meta.xml
<CustomField>
    <fullName>Feature_4__c</fullName>
    <label>Feature 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/Feature_5__c.field-meta.xml
<CustomField>
    <fullName>Feature_5__c</fullName>
    <label>Feature 5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/Feature_6__c.field-meta.xml
<CustomField>
    <fullName>Feature_6__c</fullName>
    <label>Feature 6</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/FullBathrooms_hz__c.field-meta.xml
<CustomField>
    <fullName>FullBathrooms_hz__c</fullName>
    <label>Bathrooms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/Furnished__c.field-meta.xml
<CustomField>
    <fullName>Furnished__c</fullName>
    <label>Furnished</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Partly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/Listing_Agent_Phone__c.field-meta.xml
<CustomField>
    <fullName>Listing_Agent_Phone__c</fullName>
    <label>Listing Agent Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/ListingPrice_hz__c.field-meta.xml
<CustomField>
    <fullName>ListingPrice_hz__c</fullName>
    <label>Price</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/ListingType__c.field-meta.xml
<CustomField>
    <fullName>ListingType__c</fullName>
    <label>Listing Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Rent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/Property_Propertyfinder__c.field-meta.xml
<CustomField>
    <fullName>Property_Propertyfinder__c</fullName>
    <label>Property - Propertyfinder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/PropertyType__c.field-meta.xml
<CustomField>
    <fullName>PropertyType__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>Townhouse</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Duplex</fullName>
            </value>
            <value>
                <fullName>Penthouse</fullName>
            </value>
            <value>
                <fullName>Land</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Commercial Lease</fullName>
            </value>
            <value>
                <fullName>Commercial Sale</fullName>
            </value>
            <value>
                <fullName>Business/Commercial</fullName>
            </value>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Residential Lease</fullName>
            </value>
            <value>
                <fullName>Residential Rental</fullName>
            </value>
            <value>
                <fullName>Waterfront</fullName>
            </value>
            <value>
                <fullName>Farm</fullName>
            </value>
            <value>
                <fullName>Boat Dock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/Rent_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Rent_Frequency__c</fullName>
    <label>Rent Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Half Yearly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/RERA_Permit_Number__c.field-meta.xml
<CustomField>
    <fullName>RERA_Permit_Number__c</fullName>
    <description>Trakheesi Permit Number / Listing Permit Number</description>
    <label>RERA Permit Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/Title_Arabic__c.field-meta.xml
<CustomField>
    <fullName>Title_Arabic__c</fullName>
    <label>Title (Arabic)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/TotalArea_hz__c.field-meta.xml
<CustomField>
    <fullName>TotalArea_hz__c</fullName>
    <label>Size</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Portal__c/Portal__c.object-meta.xml
<CustomObject>
    <label>Portal</label>
    <nameField>
        <label>Portal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PortalListing__c/PortalListing__c.object-meta.xml
<CustomObject>
    <label>Portal Listing</label>
    <nameField>
        <displayFormat>PortalListing-{0000000}</displayFormat>
        <label>Portal Listing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Listings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PortalListing__c/fields/Listing_hz__c.field-meta.xml
<CustomField>
    <fullName>Listing_hz__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Listing</label>
    <referenceTo>Listing_hz__c</referenceTo>
    <relationshipLabel>Listed on these portals</relationshipLabel>
    <relationshipName>Portal_Listings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PortalListing__c/fields/Portal__c.field-meta.xml
<CustomField>
    <fullName>Portal__c</fullName>
    <label>Portal</label>
    <referenceTo>Portal__c</referenceTo>
    <relationshipLabel>Listings on this Portal</relationshipLabel>
    <relationshipName>PortalListings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PortalListing__c/fields/SystemIsActive__c.field-meta.xml
<CustomField>
    <fullName>SystemIsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/Property_hz__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_hz__c/fields/Bedrooms_hz__c.field-meta.xml
<CustomField>
    <fullName>Bedrooms_hz__c</fullName>
    <label>Bedrooms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/City_Propertyfinder__c.field-meta.xml
<CustomField>
    <fullName>City_Propertyfinder__c</fullName>
    <label>City - Propertyfinder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/PropertyType__c.field-meta.xml
<CustomField>
    <fullName>PropertyType__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Duplex</fullName>
            </value>
            <value>
                <fullName>Condo</fullName>
            </value>
            <value>
                <fullName>Townhouse</fullName>
            </value>
            <value>
                <fullName>Penthouse</fullName>
            </value>
            <value>
                <fullName>Single Family</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Multi Family</fullName>
            </value>
            <value>
                <fullName>Lot/Land</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Coop</fullName>
            </value>
            <value>
                <fullName>Manufactured</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/Sub_Community_Propertyfinder__c.field-meta.xml
<CustomField>
    <fullName>Sub_Community_Propertyfinder__c</fullName>
    <label>Sub Community - Propertyfinder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/TotalArea_hz__c.field-meta.xml
<CustomField>
    <fullName>TotalArea_hz__c</fullName>
    <label>Size</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/recordTypes/Property.recordType-meta.xml
<RecordType>
    <fullName>Property</fullName>
    <active>true</active>
    <label>Property</label>
</RecordType>

force-app/main/default/objects/PropertyMedia__c/PropertyMedia__c.object-meta.xml
<CustomObject>
    <label>Property Media</label>
    <nameField>
        <label>Property Media Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Media</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PropertyMedia__c/fields/ExternalLink__c.field-meta.xml
<CustomField>
    <fullName>ExternalLink__c</fullName>
    <label>External Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PropertyMedia__c/fields/FilenameUrlEncoded__c.field-meta.xml
<CustomField>
    <fullName>FilenameUrlEncoded__c</fullName>
    <label>FilenameUrlEncoded</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PropertyMedia__c/fields/IsOnPortalFeed__c.field-meta.xml
<CustomField>
    <fullName>IsOnPortalFeed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Portal Feeds</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PropertyMedia__c/fields/Property_hz__c.field-meta.xml
<CustomField>
    <fullName>Property_hz__c</fullName>
    <label>Property</label>
    <referenceTo>Property_hz__c</referenceTo>
    <relationshipLabel>Property Media</relationshipLabel>
    <relationshipName>PropertyMedia</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PropertyMedia__c/fields/SortOnPortalFeed__c.field-meta.xml
<CustomField>
    <fullName>SortOnPortalFeed__c</fullName>
    <defaultValue>9999</defaultValue>
    <label>Sort on Portal Feed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PropertyMedia__c/fields/Tags__c.field-meta.xml
<CustomField>
    <fullName>Tags__c</fullName>
    <label>Tags</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Floorplan</fullName>
            </value>
            <value>
                <fullName>Virtual Tour</fullName>
            </value>
            <value>
                <fullName>360tour</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/XMLFeedGenerator.cls
public class XMLFeedGenerator {
    public String recordID;
    public String xmlstring { get; set; }

    public XMLFeedGenerator() {
        
        if(!Test.isRunningTest()){
        	recordID = ApexPages.currentPage().getParameters().get('Id').escapeHtml4();
        }
        Set<Id> ListingIds = new Set<Id>();
        
        List<PortalListing__c> PortalListings;

        if(!Test.isRunningTest()){
            PortalListings = [Select Id, Listing_hz__c, Portal__c, Portal__r.LastModifiedDate from PortalListing__c Where Portal__c =: recordID AND SystemIsActive__c = True];
        }
        else {
            PortalListings = [Select Id, Listing_hz__c, Portal__c, Portal__r.LastModifiedDate from PortalListing__c LIMIT 10];
        }
        
        //List<PortalListing__c> PortalListings = [Select Id, Listing_hz__c, Portal__c, Portal__r.LastModifiedDate from PortalListing__c Where Portal__c =: recordID AND SystemIsActive__c = True];
        for (PortalListing__c PortalList : PortalListings) {
            if (PortalList.Listing_hz__c != null) {
                ListingIds.add(PortalList.Listing_hz__c);
            }
        }
        List<String> fieldNames = getFieldNamesFromFieldSet('Listing_hz__c', 'FieldsForBayut');
        System.debug('Field Names: ' + fieldNames);
        String query = generateDynamicQuery(fieldNames, ListingIds);

        List<SObject> records = Database.query(query);

        Set<Id> PropertyIds = new Set<Id>();
        for (SObject record : records) {
            Id propertyId = (Id)record.get('Property_hz__c');
            if (propertyId != null) {
                PropertyIds.add(propertyId);
            }
        }

        // Map to store PropertyMedia__c records related to each Property_hz__c
        Map<Id, List<PropertyMedia__c>> propertyMediaUrlsMap = new Map<Id, List<PropertyMedia__c>>();
        for (PropertyMedia__c media : [SELECT FilenameUrlEncoded__c, ExternalLink__c, SortOnPortalFeed__c, Property_hz__c, LastModifiedDate, Tags__c FROM PropertyMedia__c WHERE Property_hz__c IN :PropertyIds AND IsOnPortalFeed__c = true Order BY SortOnPortalFeed__c ASC NULLS LAST, Name ASC]) {
            if (!propertyMediaUrlsMap.containsKey(media.Property_hz__c)) {
                propertyMediaUrlsMap.put(media.Property_hz__c, new List<PropertyMedia__c>());
            }
            propertyMediaUrlsMap.get(media.Property_hz__c).add(media);
        }

        DOM.Document doc = new DOM.Document();
        dom.XmlNode rootNode = doc.createRootElement('Properties', null, null);

        for (SObject record : records) {

            boolean hasFeatureValues = false;
            for (String fieldName : fieldNames) {
                if (fieldName.startsWith('Feature_')) {
                    Object fieldValue = record.get(fieldName);
                    if (fieldValue != null) {
                        hasFeatureValues = true;
                        break;
                    }
                }
            }

            dom.XmlNode propertyNode = rootNode.addChildElement('Property', null, null);
            
            for (String fieldName : fieldNames) {
                if(fieldName != 'Feature_1__c' && 
                   fieldName != 'Feature_2__c' && 
                   fieldName != 'Feature_3__c' && 
                   fieldName != 'Feature_4__c' && 
                   fieldName != 'Feature_5__c' && 
                   fieldName != 'Feature_6__c'){
                    Object fieldValue = record.get(fieldName);
    
                    if (fieldValue != null) {
                        dom.XmlNode fieldNode = propertyNode.addChildElement(fieldName, null, null);
                        fieldNode.addTextNode(String.valueOf(fieldValue));
                    }
                }
            }

            if (hasFeatureValues) {
                dom.XmlNode feature = propertyNode.addChildElement('Features', null, null);
                
                for (String fieldName : fieldNames) {
                    if(fieldName == 'Feature_1__c' || 
                    fieldName == 'Feature_2__c' || 
                    fieldName == 'Feature_3__c' || 
                    fieldName == 'Feature_4__c' || 
                    fieldName == 'Feature_5__c' || 
                    fieldName == 'Feature_6__c'){
                        Object fieldValue = record.get(fieldName);
        
                        // Check for null before adding text node
                        if (fieldValue != null) {
                            dom.XmlNode fieldNode = feature.addChildElement(fieldName, null, null);
                            fieldNode.addTextNode(String.valueOf(fieldValue));
                        }
                    }
                }
            }

            String lastModifiedDate = '';
            if (record.get('LastModifiedDate') != null) {
                Datetime lastModifiedDatetime = (Datetime)record.get('LastModifiedDate');
                lastModifiedDate = lastModifiedDatetime.format('yyyy-MM-dd HH:mm:ss');
            }
            
            dom.XmlNode lastupdate = propertyNode.addChildElement('Last_Updated', null, null);
            lastupdate.addTextNode(lastModifiedDate);

            // Include image URLs from map
            if (propertyMediaUrlsMap.containsKey((Id)record.get('Property_hz__c'))) {
                dom.XmlNode ImageNode = propertyNode.addChildElement('Images', null, null);
                dom.XmlNode AllNode = null;
                dom.XmlNode FloorNode = null;
                dom.XmlNode VideoNode = null;
                for (PropertyMedia__c media : propertyMediaUrlsMap.get((Id)record.get('Property_hz__c'))) {
                    String imageUrl = String.isNotBlank(media.ExternalLink__c) ? media.ExternalLink__c : media.FilenameUrlEncoded__c;
                    if (media.Tags__c != null) {
                        List<String> tagsList = media.Tags__c.split(';');
                        for (String tag : tagsList) {
                            if (tag == 'Floorplan') {
                                if (FloorNode == null) {
                                    FloorNode = propertyNode.addChildElement('Floor_Plans', null, null);
                                }
                                dom.XmlNode fieldNodeImage = FloorNode.addChildElement('Floor_Plan', null, null);
                                fieldNodeImage.addTextNode(imageUrl);
                            } else if (tag == 'Virtual Tour' || tag == '360tour') {
                                if (VideoNode == null) {
                                    VideoNode = propertyNode.addChildElement('Videos', null, null);
                                }
                                dom.XmlNode fieldNodeImage = VideoNode.addChildElement('Video', null, null);
                                fieldNodeImage.addTextNode(imageUrl);
                            }
                        }
                    }   else {
                        dom.XmlNode fieldNodeImage = ImageNode.addChildElement('Image', null, null);
                        fieldNodeImage.addTextNode(imageUrl);
                    }
                }
            }
            
            dom.XmlNode Portal = propertyNode.addChildElement('Portals', null, null);
            dom.XmlNode PortalValue1 = Portal.addChildElement('Portal', null, null);
            PortalValue1.addTextNode('Bayut');
            
        }

        xmlstring = escapeXml(doc.toXmlString());
        System.debug('xmlstring-->' + xmlstring);
    }

    public List<String> getFieldNamesFromFieldSet(String objectApiName, String fieldSetName) {
        List<String> fieldNames = new List<String>();

        try {
            // Retrieve the SObjectType for the given object API name
            Schema.SObjectType objectType = Schema.getGlobalDescribe().get(objectApiName);
            if (objectType != null) {
                // Get the fieldset map for the given object type
                Map<String, Schema.FieldSet> fieldSetMap = objectType.getDescribe().fieldSets.getMap();

                // Check if the fieldset with the given name exists
                if (fieldSetMap.containsKey(fieldSetName)) {
                    // Get the fields from the fieldset
                    List<Schema.FieldSetMember> fieldSetMembers = fieldSetMap.get(fieldSetName).getFields();

                    // Extract field names and add them to the list
                    for (Schema.FieldSetMember fieldSetMember : fieldSetMembers) {
                        fieldNames.add(fieldSetMember.getFieldPath());
                    }
                }
            }
        } catch (Exception e) {
            // Handle exceptions as needed
            System.debug('Exception: ' + e.getMessage());
        }

        return fieldNames;
    }

    public String generateDynamicQuery(List<String> fieldNames, Set<Id> ListingIds) {
        String query = 'SELECT Id, Property_hz__c, LastModifiedDate';

        for (String fieldName : fieldNames) {
            query += ', ' + fieldName;
        }

        query += ' FROM Listing_hz__c WHERE Id IN :ListingIds';

        return query;
    }
    
    // Function to escape special characters
    private String escapeXml(String input) {
        Map<String, String> replacements = new Map<String, String>{
            'Broker_s_Listing_ID__c' => 'Property_Ref_No',
            'ListingType__c' => 'Property_purpose',
            'PropertyType__c' => 'Property_Type',
            'City_Propertyfinder__c' => 'City',
            'Community_Propertyfinder__c' => 'Locality',
            'Sub_Community_Propertyfinder__c' => 'Sub_Locality',
            'Property_Propertyfinder__c' => 'Tower_name',
            'Name' => 'Property_Title',
            'Title_Arabic__c' => 'Property_Title_AR',
            'Description_hz__c' => 'Property_Description',
            'Description_Arabic__c' => 'Property_Description_AR',
            'TotalArea_hz__c' => 'Property_Size',
            'Bedrooms_hz__c' => 'Bedrooms',
            'FullBathrooms_hz__c' => 'Bathroom',
            'ListingPrice_hz__c' => 'Price',
            'Listing_Agent_Full_Property_Title__c' => 'Listing_Agent',
            'Listing_Agent_Phone__c' => 'Listing_Agent_Phone',
            'Listing_Agent_Email__c' => 'Listing_Agent_Email',
            'Feature_1__c' => 'Feature',
            'Feature_2__c' => 'Feature',
            'Feature_3__c' => 'Feature',
            'Feature_4__c' => 'Feature',
            'Feature_5__c' => 'Feature',
            'Feature_6__c' => 'Feature',
            'RERA_Permit_Number__c' => 'Permit_Number',
            'Off_Plan_New__c' => 'Off_Plan',
            'Rent_Frequency__c' => 'Rent_Frequency',
            'Furnished__c' => 'Furnished'
        };
        
        for (String key : replacements.keySet()) {
            input = input.replace(key, replacements.get(key));
        }

        return input;
    }
}