force-app/main/default/objects/Listing_hz__c/Listing_hz__c.object-meta.xml
<CustomObject>
    <label>Listing</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Listing_hz__c/fields/Broker_s_Listing_ID__c.field-meta.xml
<CustomField>
    <fullName>Broker_s_Listing_ID__c</fullName>
    <label>Broker&apos;s Listing ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/Completion_Status__c.field-meta.xml
<CustomField>
    <fullName>Completion_Status__c</fullName>
    <label>Completion Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Off Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/Description_hz__c.field-meta.xml
<CustomField>
    <fullName>Description_hz__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/FullBathrooms_hz__c.field-meta.xml
<CustomField>
    <fullName>FullBathrooms_hz__c</fullName>
    <label>Bathrooms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/ListingPrice_hz__c.field-meta.xml
<CustomField>
    <fullName>ListingPrice_hz__c</fullName>
    <label>Price</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/ListingType__c.field-meta.xml
<CustomField>
    <fullName>ListingType__c</fullName>
    <label>Listing Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Rent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/Property_Propertyfinder__c.field-meta.xml
<CustomField>
    <fullName>Property_Propertyfinder__c</fullName>
    <label>Property - Propertyfinder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/PropertyType__c.field-meta.xml
<CustomField>
    <fullName>PropertyType__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>Townhouse</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Duplex</fullName>
            </value>
            <value>
                <fullName>Penthouse</fullName>
            </value>
            <value>
                <fullName>Land</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Commercial Lease</fullName>
            </value>
            <value>
                <fullName>Commercial Sale</fullName>
            </value>
            <value>
                <fullName>Business/Commercial</fullName>
            </value>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Residential Lease</fullName>
            </value>
            <value>
                <fullName>Residential Rental</fullName>
            </value>
            <value>
                <fullName>Waterfront</fullName>
            </value>
            <value>
                <fullName>Farm</fullName>
            </value>
            <value>
                <fullName>Boat Dock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/RERA_Permit_Number__c.field-meta.xml
<CustomField>
    <fullName>RERA_Permit_Number__c</fullName>
    <description>Trakheesi Permit Number / Listing Permit Number</description>
    <label>RERA Permit Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listing_hz__c/fields/TotalArea_hz__c.field-meta.xml
<CustomField>
    <fullName>TotalArea_hz__c</fullName>
    <label>Size</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/Property_hz__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_hz__c/fields/Address_hz__c.field-meta.xml
<CustomField>
    <fullName>Address_hz__c</fullName>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/Area_hz__c.field-meta.xml
<CustomField>
    <fullName>Area_hz__c</fullName>
    <label>Area</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/Bedrooms_hz__c.field-meta.xml
<CustomField>
    <fullName>Bedrooms_hz__c</fullName>
    <label>Bedrooms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/City_Dubizzle__c.field-meta.xml
<CustomField>
    <fullName>City_Dubizzle__c</fullName>
    <label>City - Dubizzle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dubai</fullName>
            </value>
            <value>
                <fullName>Abu Dhabi</fullName>
            </value>
            <value>
                <fullName>Cairo</fullName>
            </value>
            <value>
                <fullName>Alexandria</fullName>
            </value>
            <value>
                <fullName>Jeddah</fullName>
            </value>
            <value>
                <fullName>Riyadh</fullName>
            </value>
            <value>
                <fullName>Ras al Khaimeh</fullName>
            </value>
            <value>
                <fullName>Sharjah</fullName>
            </value>
            <value>
                <fullName>Fujeirah</fullName>
            </value>
            <value>
                <fullName>Ajman</fullName>
            </value>
            <value>
                <fullName>Umm al Quwain</fullName>
            </value>
            <value>
                <fullName>Dammam and Khobar</fullName>
            </value>
            <value>
                <fullName>Kuwait City</fullName>
            </value>
            <value>
                <fullName>Doha</fullName>
            </value>
            <value>
                <fullName>Manama</fullName>
            </value>
            <value>
                <fullName>Muscat</fullName>
            </value>
            <value>
                <fullName>Damascus</fullName>
            </value>
            <value>
                <fullName>Amman</fullName>
            </value>
            <value>
                <fullName>Beirut</fullName>
            </value>
            <value>
                <fullName>Algiers</fullName>
            </value>
            <value>
                <fullName>Tripoli</fullName>
            </value>
            <value>
                <fullName>Tunis</fullName>
            </value>
            <value>
                <fullName>Casablanca</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/City_hz__c.field-meta.xml
<CustomField>
    <fullName>City_hz__c</fullName>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/City_Propertyfinder__c.field-meta.xml
<CustomField>
    <fullName>City_Propertyfinder__c</fullName>
    <label>City - Propertyfinder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/CompletionDate_hz__c.field-meta.xml
<CustomField>
    <fullName>CompletionDate_hz__c</fullName>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/Property_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Sub_Type__c</fullName>
    <label>Property Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Residential - Apartment</fullName>
            </value>
            <value>
                <fullName>Residential - Bulk Units</fullName>
            </value>
            <value>
                <fullName>Residential - Bungalow</fullName>
            </value>
            <value>
                <fullName>Residential - Compound</fullName>
            </value>
            <value>
                <fullName>Residential - Duplex</fullName>
            </value>
            <value>
                <fullName>Residential - Full floor</fullName>
            </value>
            <value>
                <fullName>Residential - Half floor</fullName>
            </value>
            <value>
                <fullName>Residential - Land</fullName>
            </value>
            <value>
                <fullName>Residential - Penthouse</fullName>
            </value>
            <value>
                <fullName>Residential - Townhouse</fullName>
            </value>
            <value>
                <fullName>Residential - Villa</fullName>
            </value>
            <value>
                <fullName>Residential - Whole Building</fullName>
            </value>
            <value>
                <fullName>Residential - Labor Camp</fullName>
            </value>
            <value>
                <fullName>Commercial - Bulk Units</fullName>
            </value>
            <value>
                <fullName>Commercial - Full floor</fullName>
            </value>
            <value>
                <fullName>Commercial - Half floor</fullName>
            </value>
            <value>
                <fullName>Commercial - Office Space</fullName>
            </value>
            <value>
                <fullName>Commercial - Plot</fullName>
            </value>
            <value>
                <fullName>Commercial - Retail</fullName>
            </value>
            <value>
                <fullName>Commercial - Shop</fullName>
            </value>
            <value>
                <fullName>Commercial - Show Room</fullName>
            </value>
            <value>
                <fullName>Commercial - Staff Accommodation</fullName>
            </value>
            <value>
                <fullName>Commercial - Villa</fullName>
            </value>
            <value>
                <fullName>Commercial - Warehouse</fullName>
            </value>
            <value>
                <fullName>Commercial - Whole Building</fullName>
            </value>
            <value>
                <fullName>Commercial - Labor Camp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/PropertyType__c.field-meta.xml
<CustomField>
    <fullName>PropertyType__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apartment</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Duplex</fullName>
            </value>
            <value>
                <fullName>Condo</fullName>
            </value>
            <value>
                <fullName>Townhouse</fullName>
            </value>
            <value>
                <fullName>Penthouse</fullName>
            </value>
            <value>
                <fullName>Single Family</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>Multi Family</fullName>
            </value>
            <value>
                <fullName>Lot/Land</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Coop</fullName>
            </value>
            <value>
                <fullName>Manufactured</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/State_hz__c.field-meta.xml
<CustomField>
    <fullName>State_hz__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/Sub_Community_Propertyfinder__c.field-meta.xml
<CustomField>
    <fullName>Sub_Community_Propertyfinder__c</fullName>
    <label>Sub Community - Propertyfinder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/fields/TotalArea_hz__c.field-meta.xml
<CustomField>
    <fullName>TotalArea_hz__c</fullName>
    <label>Size</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property_hz__c/recordTypes/Property.recordType-meta.xml
<RecordType>
    <fullName>Property</fullName>
    <active>true</active>
    <label>Property</label>
</RecordType>

force-app/main/default/objects/PropertyMedia__c/PropertyMedia__c.object-meta.xml
<CustomObject>
    <label>Property Media</label>
    <nameField>
        <label>Property Media Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Media</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PropertyMedia__c/fields/FilenameUrlEncoded__c.field-meta.xml
<CustomField>
    <fullName>FilenameUrlEncoded__c</fullName>
    <label>FilenameUrlEncoded</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PropertyMedia__c/fields/Property_hz__c.field-meta.xml
<CustomField>
    <fullName>Property_hz__c</fullName>
    <label>Property</label>
    <referenceTo>Property_hz__c</referenceTo>
    <relationshipLabel>Property Media</relationshipLabel>
    <relationshipName>PropertyMedia</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PropertyMedia__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UploadControllerTest.cls
@isTest
public with sharing class UploadControllerTest {
     
    @isTest
    static void testFetchData() {

        Property_hz__c pro=new Property_hz__c();
        pro.name ='test';
        pro.Address_hz__c ='Test';
        pro.Area_hz__c ='Test';
        insert pro;

        PropertyMedia__c propertyMedia = new PropertyMedia__c(
            Name = 'Test Media',
            FilenameUrlEncoded__c = 'test_url',
            Size__c = 1024,
            Property_hz__c = pro.Id
        );
        insert propertyMedia;

        List<PropertyMedia__c> result = uploadController.fetchdata(propertyMedia.Property_hz__c);

        System.assertEquals(1, result.size(), 'Expected one record');
    }

    @isTest
    static void testFetchDataForListing() {


        Account testAccount1 = new Account(Name='Test Account 1');
        insert testAccount1;

        Contact testContact1 = new Contact(FirstName='Vansh', LastName='Mehra', AccountId=testAccount1.Id,ContactType_hz__c='Landlord',Stage__c='Active',Stage_hz__c='Off-Market', Email='vansh@houzon.com');
        insert testContact1; 
        
        Property_hz__c pro=new Property_hz__c();
        pro.name ='test';
        pro.Address_hz__c ='Test';
        pro.Area_hz__c ='Test';
        insert pro;

        Listing_hz__c listingRecord1 = new Listing_hz__c();
        listingRecord1.Name = 'Test1';
        listingRecord1.Status__c = 'Active';
        listingRecord1.ListingType__c = 'Rental';
        listingRecord1.PropertyType__c = 'Apartment';
        listingRecord1.Bedrooms_hz__c = 2;
        listingRecord1.FullBathrooms_hz__c = 2;
        listingRecord1.ListingPrice_hz__c = 1000;
        listingRecord1.City_hz__c = 'Test';
        listingRecord1.State_hz__c = 'Test';
        listingRecord1.Broker_s_Listing_ID__c='Test';
        listingRecord1.Houzon_Broker_s_Listing_ID__c='Test1';
        listingRecord1.Description_hz__c='Testing Area';
        listingRecord1.PropertySubType_hz__c='Industrial';
        listingRecord1.Property_Sub_Type__c='Residential - Apartment';
        listingRecord1.RERA_Permit_Number__c='100';
        listingRecord1.TotalArea_hz__c=1000;
        listingRecord1.Sub_Community_Propertyfinder__c='Test';
        listingRecord1.Community_Propertyfinder__c='Test';
        listingRecord1.Property_Propertyfinder__c='Test';
        listingRecord1.LocationText_Dubizzle__c='Test';
        listingRecord1.City_Propertyfinder__c='test';
        listingRecord1.Price_Unit__c='Price Yearly';
        listingRecord1.Completion_Status__c='Completed';
        listingRecord1.City_Dubizzle__c='Test';
        listingRecord1.Property_Status__c='Vacant on Transfer';
        listingRecord1.Available_from__c=date.today()+1;
        listingRecord1.CompletionDate_hz__c=date.today()+1;
        listingRecord1.PropertyOwnerContact__c=testContact1.Id;
        listingRecord1.Property_hz__c=pro.Id;
        listingRecord1.property_category__c='Commercial';
        insert listingRecord1;

        

        PropertyMedia__c propertyMedia = new PropertyMedia__c(
            Name = 'Test Media',
            FilenameUrlEncoded__c = 'test_url',
            Size__c = 1024,
            Property_hz__c = pro.Id
        );
        insert propertyMedia;

        uploadController.getListingRecord(listingRecord1.Id);


        List<PropertyMedia__c> result = uploadController.fetchdataforlisting(listingRecord1.Id);
        Boolean result1 = uploadController.deletelistingmedia(null, listingRecord1.Id);
        Boolean result2 = uploadController.deletemedia(propertyMedia.Id, null);
        Boolean result3 = uploadController.createmediaforlisting('Test Media', 10.0, listingRecord1.Id, 'https://example.com/test');
        List<PropertyMedia__c> mediaList = [SELECT Id FROM PropertyMedia__c WHERE Id = :propertyMedia.Id];
        Boolean result5 = uploadController.updateSortOrder(mediaList);
        PropertyMedia__c propertyMedia2 = new PropertyMedia__c(
            Name = 'Test Media',
            FilenameUrlEncoded__c = 'test_url',
            Size__c = 1024,
            Property_hz__c = pro.Id
        );
        insert propertyMedia2;
        propertyMedia2.Name = 'Test Media2';
        update propertyMedia2;
        Boolean result6 = uploadController.updateOrderState(new List<Id>{propertyMedia2.Id}, new List<Id>(), new List<Id>(),new List<Id>(),new List<Id>(),new List<Id>());
        PropertyMedia__c propertyMedia1 = new PropertyMedia__c(
            Name = 'Test Media',
            FilenameUrlEncoded__c = 'test_url',
            Size__c = 1024,
            Property_hz__c = pro.Id
        );
        insert propertyMedia1;

        Boolean result7 = uploadController.updateOrderState_toFalse(new List<Id>(), new List<Id>{propertyMedia1.Id}, new List<Id>());

    }

    @isTest
    static void testCreateMedia() {
        String propertyName = 'Test Property';
        Decimal fileSize = 1024;
        String url = 'test_url';
        String externalLink = 'external_link';

        Property_hz__c pro=new Property_hz__c();
        pro.name ='test';
        pro.Address_hz__c ='Test';
        pro.Area_hz__c ='Test';
        insert pro;


        Boolean result = uploadController.createmedia(propertyName, fileSize, pro.Id, url, externalLink);



        System.assertEquals(true, result, 'Expected creation success');

        List<PropertyMedia__c> insertedMedia = [SELECT Id FROM PropertyMedia__c WHERE Name = :propertyName AND Property_hz__c = :pro.Id];
        System.assertEquals(1, insertedMedia.size(), 'Expected one record inserted');
        S3Service.getS3ConfigSettings();

    }
    @isTest
    static void deletePromedia() {


        Account testAccount1 = new Account(Name='Test Account 1');
        insert testAccount1;

        Contact testContact1 = new Contact(FirstName='Vansh', LastName='Mehra', AccountId=testAccount1.Id,ContactType_hz__c='Landlord',Stage__c='Active',Stage_hz__c='Off-Market', Email='vansh@houzon.com');
        insert testContact1; 
        
        Property_hz__c pro=new Property_hz__c();
        pro.name ='test';
        pro.Address_hz__c ='Test';
        pro.Area_hz__c ='Test';
        insert pro;

        Listing_hz__c listingRecord1 = new Listing_hz__c();
        listingRecord1.Name = 'Test1';
        listingRecord1.Status__c = 'Active';
        listingRecord1.ListingType__c = 'Rental';
        listingRecord1.PropertyType__c = 'Apartment';
        listingRecord1.Bedrooms_hz__c = 2;
        listingRecord1.FullBathrooms_hz__c = 2;
        listingRecord1.ListingPrice_hz__c = 1000;
        listingRecord1.City_hz__c = 'Test';
        listingRecord1.State_hz__c = 'Test';
        listingRecord1.Broker_s_Listing_ID__c='Test';
        listingRecord1.Description_hz__c='Testing Area';
        listingRecord1.PropertySubType_hz__c='Industrial';
        listingRecord1.Houzon_Broker_s_Listing_ID__c='Test1';
        listingRecord1.Property_Sub_Type__c='Residential - Apartment';
        listingRecord1.RERA_Permit_Number__c='100';
        listingRecord1.TotalArea_hz__c=1000;
        listingRecord1.Sub_Community_Propertyfinder__c='Test';
        listingRecord1.Community_Propertyfinder__c='Test';
        listingRecord1.Property_Propertyfinder__c='Test';
        listingRecord1.LocationText_Dubizzle__c='Test';
        listingRecord1.City_Propertyfinder__c='test';
        listingRecord1.Price_Unit__c='Price Yearly';
        listingRecord1.Completion_Status__c='Completed';
        listingRecord1.City_Dubizzle__c='Test';
        listingRecord1.Property_Status__c='Vacant on Transfer';
        listingRecord1.Available_from__c=date.today()+1;
        listingRecord1.CompletionDate_hz__c=date.today()+1;
        listingRecord1.PropertyOwnerContact__c=testContact1.Id;
        listingRecord1.Property_hz__c=pro.Id;
        listingRecord1.property_category__c='Commercial';
        insert listingRecord1;

        
        Decimal newSize = 200;
        PropertyMedia__c propertyMedia = new PropertyMedia__c(
            Name = 'Test Media',
            FilenameUrlEncoded__c = 'test_url',
            Size__c = 1024,
            Property_hz__c = pro.Id,
            Tags__c='tag1;tag2'
        );
        insert propertyMedia;
        
        Boolean result4 = uploadController.update_media_name(propertyMedia.Id, 'Test Media','test_url',new List<String>{'tag3', 'tag4'},null,propertyMedia.Size__c); 
        
        PropertyMedia__c propertyMedia1 = new PropertyMedia__c(
            Name = 'Test Media',
            FilenameUrlEncoded__c = 'test_url',
            Size__c = 1024,
            Property_hz__c = pro.Id
        );
        insert propertyMedia1;
        propertyMedia1.name='Test Media1';
        update propertyMedia1;

        Boolean result5 = uploadController.update_media_name(propertyMedia1.Id, 'Test Media1','test_url',new List<String>{'tag3', 'tag4'},null,propertyMedia1.Size__c);
    }
    @isTest
    static void testGetListingRecord_Exception() {
        Test.startTest();
        try {
            uploadController.getListingRecord('invalidId');
            System.assert(false, 'Expected exception was not thrown');
        } catch (AuraHandledException e) {
        }
        Test.stopTest();
    }
}