force-app/main/default/objects/ForceSiteURL__c/ForceSiteURL__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Force.com Site Url</description>
    <label>ForceSiteURL</label>
</CustomObject>

force-app/main/default/objects/ForceSiteURL__c/fields/SiteUrl__c.field-meta.xml
<CustomField>
    <fullName>SiteUrl__c</fullName>
    <label>SiteUrl</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Portal__c/Portal__c.object-meta.xml
<CustomObject>
    <label>Portal</label>
    <nameField>
        <label>Portal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portal__c/fields/generator__c.field-meta.xml
<CustomField>
    <fullName>generator__c</fullName>
    <label>Generator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dubizzle</fullName>
            </value>
            <value>
                <fullName>XML2U</fullName>
            </value>
            <value>
                <fullName>Propertyfinder</fullName>
            </value>
            <value>
                <fullName>1001Portales</fullName>
            </value>
            <value>
                <fullName>Rightmove</fullName>
            </value>
            <value>
                <fullName>Bayut</fullName>
            </value>
            <value>
                <fullName>Generic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Portal__c/fields/XML_Feed_URL__c.field-meta.xml
<CustomField>
    <fullName>XML_Feed_URL__c</fullName>
    <description>As admin, after creating a new portal, save the Manda URL in here, so you have it handy when you need it.
https://manda.propertybase.com/feed/00Db_YOUR_18DIGIT_ORG_ID_0CCCCCC/propertyfinder/a0hb_18_Digit_Portal_Record_ID_0BBBBBBBB
How to build a feed URL: https://help.propertybase.com/hc/en-us/articles/202899016-Middle-East-Property-Portal-Integration</description>
    <inlineHelpText>XML Feed URL value depends on the Generator field.</inlineHelpText>
    <label>XML Feed URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/PortalTriggerHandler.cls
public with sharing class PortalTriggerHandler {
    public void OnBeforeUpdate(Portal__c[] newPortal){
        ForceSiteURL__c forceSiteURL = ForceSiteURL__c.getOrgDefaults();
        System.debug('forceSiteURL---->'+forceSiteURL);
        for (Portal__c portal : newPortal) {
            if (portal.generator__c == 'Propertyfinder') {
                portal.XML_Feed_URL__c = forceSiteURL.SiteUrl__c + 'XMLFeedForPF?Id=' + portal.ID; 
            } else if (portal.generator__c == 'Bayut') {
                portal.XML_Feed_URL__c = forceSiteURL.SiteUrl__c + 'XMLFeed?Id=' + portal.ID;
            } else if (portal.generator__c == 'Dubizzle') {
                portal.XML_Feed_URL__c = forceSiteURL.SiteUrl__c + 'XMLFeedForDubizzle?Id=' + portal.ID;
            } else {
                portal.XML_Feed_URL__c = '';
            }
        }
    }

    public void OnAfterInsert(Portal__c[] newPortal) {
        List<Portal__c> portalsToUpdate = new List<Portal__c>();
        ForceSiteURL__c forceSiteURL = ForceSiteURL__c.getOrgDefaults();
        
        for (Portal__c portal : newPortal) {
            Portal__c updatedPortal = new Portal__c(
                Id = portal.Id,
                XML_Feed_URL__c = getXMLFeedURL(forceSiteURL.SiteUrl__c, portal.generator__c, portal.Id)
            );
            portalsToUpdate.add(updatedPortal);
        }
        
        update portalsToUpdate;
    }
    
    private String getXMLFeedURL(String siteUrl, String generator, Id portalId) {
        if (generator == 'Propertyfinder') {
            return siteUrl + 'XMLFeedForPF?Id=' + portalId; 
        } else if (generator == 'Bayut') {
            return siteUrl + 'XMLFeed?Id=' + portalId;
        } else if (generator == 'Dubizzle') {
            return siteUrl + 'XMLFeedForDubizzle?Id=' + portalId;
        } else {
            return '';
        }
    }
}